version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    ports:
      - "9000:9000"
    command: server /data
    environment:
        MINIO_DOMAIN: 'localhost'
        MINIO_ACCESS_KEY: 'minioadmin'
        MINIO_SECRET_KEY: 'minioadmin'
        MINIO_REGION: 'us-east-1'
    volumes:
      - ./mnt:/root/.minio